bower.json, locale/ar/LC_MESSAGES/django.po, locale/el/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, locale/fa/LC_MESSAGES/django.po, simple_ui/static/css/site.css, simple_ui/templates/base.html, simple_ui/templates/landing_page.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-8
=> Change home screen

root/settings.py, simple_ui/static/js/refugeeApp/controllers/NavigationController.js, simple_ui/templates/base.html, simple_ui/templates/landing_page.html, simple_ui/templates/navigation.html, simple_ui/views.py
https://refugeeinfo.atlassian.net/browse/RIW-17
=> Add ability to change language

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/ServiceDetailsController.js, simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/js/refugeeApp/directives/serviceMap.js, simple_ui/static/js/refugeeApp/directives/servicesList.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/templates/base.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-12
=> 12: Service details

bower.json, simple_ui/static/js/refugeeApp/directives/serviceMap.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/templates/angular/partials/location.services.html, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-13
https://refugeeinfo.atlassian.net/browse/RIW-24
=> add clustering, change to use google maps layer

simple_ui/static/js/refugeeApp/directives/regionMap.js
https://refugeeinfo.atlassian.net/browse/RIW-32
=> Show marker instead of polygon in location details

simple_ui/static/js/refugeeApp/services/LoadingOverlayService.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-41
=> 41: Animated loading screen spinner

simple_ui/static/js/refugeeApp/directives/locationMap.js
https://refugeeinfo.atlassian.net/browse/RIW-31
=> Add ability to choose location on map

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/region-choice.html, simple_ui/templates/footer.html, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-35
=> 35: Create cookie policy notification; location choice list redesigned

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/js/refugeeApp/controllers/NavigationController.js, simple_ui/static/js/refugeeApp/directives/regionChoice.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/region-choice.html, simple_ui/templates/angular/partials/location.details.html, simple_ui/templates/angular/partials/location.html, simple_ui/templates/base.html, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-43
=> 43: RTL support

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/scss/main.scss, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-18
=> Add feedback link

simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-48
I'm not sure if getting language from cookie is good performance-wise, but passing language to every API function might be not most convenient way.
=> 48: Translate service data from API

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-44
=> 44: Add missing content to service details

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/searchBar.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-27
=> Improve search in services list

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/searchBar.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-27
=> Move search bar to html file, fix bug in services map

simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-51
=> Add labels with name and descritpions in services map

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-51
=> Wrap long text in services map labels

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js
https://refugeeinfo.atlassian.net/browse/RIW-58
=> Load all services in services list view

simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-59
=> Redraw markers in services map on state change

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-60
=> Add padding to services map

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html
https://refugeeinfo.atlassian.net/browse/RIW-5
=> Make filter list scrollable

simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js
https://refugeeinfo.atlassian.net/browse/RIW-57
=> Fix blocked dialog after browser back button

simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-61
=> Remove margin from modal on mobile view

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationChoiceController.js, simple_ui/static/js/refugeeApp/directives/locationBar.js, simple_ui/templates/angular/partials/directives/location-bar.html
https://refugeeinfo.atlassian.net/browse/RIW-64
=> Fix change location

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationDetailsController.js, simple_ui/static/js/refugeeApp/directives/quickLinks.js, simple_ui/templates/angular/partials/directives/quick-links.html, simple_ui/templates/angular/partials/location.details.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.services.html, simple_ui/templates/base.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-66
=> Change default location view, move quick links to directive

bower.json, simple_ui/static/js/refugeeApp/directives/locationMap.js, simple_ui/static/js/refugeeApp/directives/regionMap.js, simple_ui/static/js/refugeeApp/directives/serviceMap.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-52
=> Add ability to zoom map on mouse rollover

simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-69
=> Set initial map region to location bounds

simple_ui/static/js/refugeeApp/directives/locationMap.js, simple_ui/static/js/refugeeApp/directives/serviceMap.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-52
=> Hide sleepNote on map

simple_ui/static/js/refugeeApp/app.js, simple_ui/templates/angular/partials/directives/location-buttons.html
https://refugeeinfo.atlassian.net/browse/RIW-66
=> Fix highlighting current path button

simple_ui/templates/angular/partials/location.home.html
https://refugeeinfo.atlassian.net/browse/RIW-75
=> Hide important info for XS screens.

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/templates/footer.html
https://refugeeinfo.atlassian.net/browse/RIW-78
=> Remove changing theme switch

bower.json, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-51
=> Added service info details div instead of label on map

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.home.html
https://refugeeinfo.atlassian.net/browse/RIW-77
=> Align icons in general info

simple_ui/static/js/refugeeApp/directives/changeLocationButton.js, simple_ui/static/js/refugeeApp/directives/locationBar.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/change-location-button.html, simple_ui/templates/angular/partials/directives/location-bar.html, simple_ui/templates/angular/partials/location.details.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/templates/angular/partials/location.services.html, simple_ui/templates/base.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-76
=> Add Important info title

simple_ui/templates/angular/partials/directives/drawer.html
https://refugeeinfo.atlassian.net/browse/RIW-83
=> 83: Fix change language on XS at change location view

simple_ui/templates/angular/partials/location.important-information.html
https://refugeeinfo.atlassian.net/browse/RIW-75
=> Hide important information on XS

simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-89
=> Remove change location button on XS screens

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/searchBar.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/templates/angular/partials/directives/search-bar.html
https://refugeeinfo.atlassian.net/browse/RIW-91
=> Search services with GET parameters

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-92
=> Fix general info error, get location slug from rootScope

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js
https://refugeeinfo.atlassian.net/browse/RIW-98
=> Fix anchor links

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/locale/en.json, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.notifications.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-101
=> Move banner to drawer on mobile

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/navigation.html
Link the logo to the info page;
Changes in CSS here and there;
Collapsing all items at the same time;
=> Reyrodrigues patch 2

.eslintrc.json, bower.json, simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/base.html, simple_ui/views.py
https://refugeeinfo.atlassian.net/browse/RIW-99
=> Sharing content feature

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/scss/main.scss, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-106
=> Fix click on logo sets location

.eslintrc.json, simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js, simple_ui/static/js/refugeeApp/directives/fbLike.js, simple_ui/static/js/refugeeApp/directives/fbShare.js, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-104
https://refugeeinfo.atlassian.net/browse/RIW-99
=> Improve facebook like and share buttons

bower.json, simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js, simple_ui/static/js/refugeeApp/directives/fbLike.js, simple_ui/static/js/refugeeApp/directives/ratingThumbs.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/fb-like.html, simple_ui/templates/angular/partials/directives/rating-thumbs.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/base.html, simple_ui/urls.py, simple_ui/views.py
https://refugeeinfo.atlassian.net/browse/RIW-100
=> Add rating content

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/directives/ratingThumbs.js, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/templates/angular/partials/directives/rating-thumbs.html, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-112
=> Fixed set location on about us, highlight chosen rating

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-116
=> Fix problem with changing language

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/locale/en.json, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-121
=> Show info on map when there are no services

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-124
=> Detect browser language

simple_ui/static/js/refugeeApp/app.js
Google analytics to track in app page views as well as which pages and services the users are looking at
=> Google Analytics

Gulpfile.js, circle.yml, simple_ui/static/js/main.js, simple_ui/static/js/refugeeApp/app.js, simple_ui/views.py
https://refugeeinfo.atlassian.net/browse/RIW-130
=> Adapt location choice screen to v2, fix some eslint errors

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/directives/regionName.js, simple_ui/static/js/refugeeApp/directives/scrollToAnchor.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-134
=> Fix map, refactor of services map

simple_ui/static/js/refugeeApp/directives/locationInfo.js, simple_ui/static/js/refugeeApp/directives/quickLinks.js, simple_ui/templates/angular/partials/directives/quick-links.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/views.py
- Important informations
- Banners
- Contents
https://refugeeinfo.atlassian.net/browse/RIW-131
=> Adapt location details screen

simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html
https://refugeeinfo.atlassian.net/browse/RIW-135
=> Adapt subsections and pop ups.

simple_ui/static/js/refugeeApp/services/LocationService.js
https://refugeeinfo.atlassian.net/browse/RIW-139
=> Adapt services in location

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-132
=> Fix about us

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-134
=> Refactor of services map, refresh site name on state change

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-132
=> Fix About Us page

simple_ui/static/js/refugeeApp/directives/print-page.js, simple_ui/static/scss/content.scss, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/print-page.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-140
=> Ability to print information and services

simple_ui/static/js/refugeeApp/app.js
Reverts theirc/web.refugee.info#191
=> Revert "Fix About Us page"

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-156
=> Styling for images in about us page

bower.json, simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/js/refugeeApp/directives/serviceMap.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/locale/en.json, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-118
=> Disable map sleep for mobile on services map, info for mobile how to wake map on service details

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/scss/content-print.scss, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-140
=> Services printing and additional content styling

simple_ui/static/scss/content.scss
https://refugeeinfo.atlassian.net/browse/RID-221
=> Try to fix octal literal error

simple_ui/static/scss/content.scss
https://refugeeinfo.atlassian.net/browse/RID-221
=> Pure CSS collapse triangle in Q&A; Second try to fix octal literal

simple_ui/static/js/refugeeApp/app.js
https://refugeeinfo.atlassian.net/browse/RIW-145
=> Fix change location by Link from CMS

package.json, root/settings.py, simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/templates/base.html, simple_ui/templates/landing_page.html, simple_ui/views.py
add facebook credentials in settings, add initial facebok data to refreshFacebookSdk function, add facebookAppId constant to refugeeApp module
=> Standarize facebook

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/locale/en.json, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-207
=> Display service provider in service details, fix eslint error

simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/directives/services-list.html
- added separators between services
- fixed filtering
=> Improve sorting services by filter

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/services/LocationService.js
Removing the URL from the service type (we track by ID now) and adapting the loading of services
=> Adapting Services to V2 Urls

simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json
https://refugeeinfo.atlassian.net/browse/RIW-210
=> Replace the name: "Directory" to "Services"

simple_ui/static/js/refugeeApp/directives/servicesMap.js
https://refugeeinfo.atlassian.net/browse/RIW-211
=> Remove clustering on map

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-213
=> Remove square placemarks and replace with RI Green standard placemarks

simple_ui/static/js/refugeeApp/directives/serviceMap.js
https://refugeeinfo.atlassian.net/browse/RIW-192
=> Manually revert changes to service details map;

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/location.services.html
- added view changing same as on mobile app  (filter, list, map buttons)
- added texts (RIW-204)
=> Improve map interaction in web

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.services.html
- Standardise font of the top bar that switches between list and map views (Web)
- Zoom buttons to be added to the (Web) map
- Showing service provider name in service listing (Web)
=> UI improvements Web

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/templates/navigation.html, simple_ui/urls.py
plus fix for change language bug
=> Back navigation from service details

simple_ui/templates/angular/partials/location.notifications.html
https://refugeeinfo.atlassian.net/browse/RIW-245
=> Banner is not appear on web mobile application

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/scss/main.scss, simple_ui/templates/navigation.html
and from service details to service mapping
https://refugeeinfo.atlassian.net/browse/RIW-252
=> Navigation from service mapping to home page

simple_ui/templates/angular/partials/location.notifications.html
https://refugeeinfo.atlassian.net/browse/RIW-245
=> Pop ups from banners on mobile devices

simple_ui/static/js/refugeeApp/controllers/BaseController.js, simple_ui/static/scss/main.scss, simple_ui/templates/navigation.html
https://refugeeinfo.atlassian.net/browse/RIW-252
=> Fix icon for back button in navigation

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/templates/angular/partials/directives/location-buttons.html
https://refugeeinfo.atlassian.net/browse/RIW-255
=> Service map button in side menu

simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-269
=> Phone number fix for rtl

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-268
=> Filter view fix for rtl

simple_ui/static/images/favicons/alkhadamat.info/manifest.json, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-272
=> Removed map recentering after clicking on marker

simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-274
=> Fix markers position change while zooming in and out

simple_ui/static/js/refugeeApp/app.js
Recording all events. Else ifs may have been filtering data unnecessary
=> Update app.js (now to develop)

simple_ui/static/js/refugeeApp/directives/collapseOnAnchorScroll.js, simple_ui/templates/angular/partials/directives/service-details.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html
https://refugeeinfo.atlassian.net/browse/RIW-292
=> Date format change in 'last updated on' info.

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
Leaving the updated at the same font size as the content. Adding span to date to render it in ltr regardless.
=> Updated At Tweaks

simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html
Rey forgot to update *all* files.
=> Updated On

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-318
=> Service Tags in service details

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
This reverts commit 69a32228effeff59adc57f100d9875c17bc7ea89.
https://refugeeinfo.atlassian.net/browse/RIW-329
=> Revert "Service Tags in service details"

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.services.html, simple_ui/templates/base.html, simple_ui/templates/navigation.html
Fix anchor links below navbar;
Fix double scrollbar in modal;
Remove autoscroll from ui-views;
=> Change main layout, modal layout to flex based;

simple_ui/static/scss/main.scss
Change background to flat color;
=> Allow to break line in service description;

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/templates/angular/partials/directives/service-details.html
Fix some console errors at Service Details screen;
=> Add translation strings for week days;

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/static/scss/main.scss, simple_ui/static/scss/mixins.scss, simple_ui/templates/angular/partials/directives/service-details.html
- Email button
- Website button
- Facebook page button
Related tickets:
https://refugeeinfo.atlassian.net/browse/RIW-333
https://refugeeinfo.atlassian.net/browse/RIW-340
https://refugeeinfo.atlassian.net/browse/RIW-354
=> Display new fields in service details

simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-336
=> Show additional information field in Service details

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html, simple_ui/templates/angular/partials/location.service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-357
=> Unified RI Web Service Details with Mobile

simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.notifications.html, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-373
=> Removed text: "Explore each of the boxes below to learn more."

simple_ui/static/js/refugeeApp/services/LocationService.js
https://refugeeinfo.atlassian.net/browse/RIW-344
=> Apply showing services on country level to all sub-levels

simple_ui/static/js/refugeeApp/directives/regionName.js, simple_ui/templates/angular/partials/directives/service-details.html, simple_ui/templates/angular/partials/directives/services-list.html
https://refugeeinfo.atlassian.net/browse/RIW-415
=> Fix issue with service region name is always choosen location.

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/LocationDetailsController.js, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/templates/angular/partials/directives/location-info.html, simple_ui/templates/angular/partials/directives/quick-links.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.services.html, simple_ui/templates/navigation.html
This reverts commit ac3bd0abe039decb3ea4e22c22a37537e29719f5.
https://refugeeinfo.atlassian.net/browse/RIW-421
=> Revert "Remove Important Information."

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-435
=> RIW-435 List of services relevant for current area on the map

simple_ui/static/js/refugeeApp/controllers/LocationDetailsController.js
https://refugeeinfo.atlassian.net/browse/RIW-437
=> RIW-437 Force to top, when going to link in important information

simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/location.services.html
- Changing "filter" in services to "Types of services"
- Make searching for services bigger/bolder in desktop view
=> RIW-425 RIW-426 Search bar improvements

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/angular/partials/directives/drawer.html
(map of services for mobile devices)
=> Active state and loading fix

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/searchBar.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/templates/angular/partials/directives/search-bar.html
(mobile devices only)
https://refugeeinfo.atlassian.net/browse/RIW-439
=> RIW-439 Service type on list only if it has services assigned

simple_ui/static/js/refugeeApp/app.js, simple_ui/static/js/refugeeApp/controllers/ServiceDetailsController.js, simple_ui/static/js/refugeeApp/directives/locationButtons.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/templates/angular/partials/directives/location-buttons.html, simple_ui/templates/angular/partials/location.home.html, simple_ui/templates/angular/partials/location.important-information.html, simple_ui/templates/angular/partials/location.service-details.html, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-436
=> RIW-436 Service Draft preview

simple_ui/templates/landing_page.html
This will do wonders to our bounce rate.
=> Removing redundant first google analytics hit.

simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-451
=> RIW-451 - Changes in address field

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/angular/partials/location.service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-452
=> RIW-452 Services without location provided.

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-455
=> RIW-455 Ability to change service pin color

simple_ui/templates/angular/partials/directives/service-details.html
- shows CLOSED if there is only one empty shift
=> Service opening time improvement

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/locationButtons.js, simple_ui/templates/angular/partials/directives/drawer.html
-  when user click on service map it will take him to filter than to list.
https://refugeeinfo.atlassian.net/browse/RIW-463
=> RIW-463 - Service list is displayed first (mobile device)

simple_ui/static/js/refugeeApp/controllers/BaseController.js
https://refugeeinfo.atlassian.net/browse/RIW-445
=> RIW - 445 - Change language with content open fix

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/locale/ar.json, simple_ui/static/locale/en.json, simple_ui/static/locale/fa.json, simple_ui/templates/angular/partials/directives/service-details.html
- added translation for AM/PM in opening time table
- added translation 24/7 open time
- added english search in "get direction" button in service mapping
- removed label for floor / note about address
https://refugeeinfo.atlassian.net/browse/RIW-482
https://refugeeinfo.atlassian.net/browse/RIW-484
=> RIW - 482, 484 - Service Details improvements

simple_ui/static/js/refugeeApp/services/LocationService.js
https://refugeeinfo.atlassian.net/browse/RIW-578
=> RIW-578 - Displaying services only for selected region and its relatives

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-579
=> RIW-579 - Ability to get directions from coordinates

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html
https://refugeeinfo.atlassian.net/browse/RIW-580
=> RIW-580 - Show multiple service types on service list

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-map.html
https://refugeeinfo.atlassian.net/browse/RIW-580
=> RIW-580 - Show multiple service types in service info on map

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html
https://refugeeinfo.atlassian.net/browse/RIW-580
=> RIW-580 - Multiple service types on lower resolutions fix

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/base.html
https://refugeeinfo.atlassian.net/browse/RIW-600
=> RIW-600 - Clicking on overlapping services (Spiderfier)

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
=> RIW-600 - Fix for not disappearing legs (spiderfier)

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-610
=> RIW-610 - Static service type list (on desktop view)

simple_ui/templates/angular/partials/directives/service-details.html
https://refugeeinfo.atlassian.net/browse/RIW-617
=> Service Details - address ordering change

bower.json, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/templates/base.html
- removed plus sign if there are no overlapping markers
=> Spiderfier - markers icon fix

simple_ui/static/js/refugeeApp/app.js, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/urls.py
https://refugeeinfo.atlassian.net/browse/RIW-624
=> Possibility to access hidden important information

simple_ui/static/js/refugeeApp/app.js, simple_ui/templates/angular/partials/directives/drawer.html, simple_ui/urls.py
* Add names before types of information to distinguish them
* Delete unnecessary spaces
=> Add names before types of information to distinguish them (#345)

simple_ui/static/js/refugeeApp/app.js
- only accepted slugs will have this possibility
https://refugeeinfo.atlassian.net/browse/RIW-624
=> Change in accessing hidden-important information

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html
=> Show the whole title, location and service provider name in a listing of

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.services.html
https://refugeeinfo.atlassian.net/browse/RIW-631
https://trello.com/c/Cjq5JBEC/35-as-a-user-once-i-click-on-a-category-and-view-it-on-whatever-map-or-list-view-and-come-back-to-service-categories-i-need-to-be-a
=> Types of services list - highlight chosen type (mobile)

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html
https://refugeeinfo.atlassian.net/browse/RIW-635
=> Markers on map and icons on list match in color

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-list.html
https://refugeeinfo.atlassian.net/browse/RIW-615
=> RIW-615 - Service listings organized by category

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.services.html
- service types sorted with ordering provided in admin panel
- Icons for multi-type services will have its own colors
https://refugeeinfo.atlassian.net/browse/RIW-615
=> RIW-615 - Service listing improvements

simple_ui/static/js/refugeeApp/services/LocationService.js
https://refugeeinfo.atlassian.net/browse/RIW-642
=> RIW-642 - Show services for chosen region and its parents only

simple_ui/static/js/refugeeApp/directives/serviceDetails.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/service-details.html
Reverts theirc/web.refugee.info#375
=> Revert "Pre-wrap in case text is not html"

simple_ui/static/scss/main.scss, simple_ui/static/scss/mixins.scss
https://trello.com/c/ey41DNDc/68-ability-to-color-text-in-service-mapping-details-and-additional-information
=> Color change for links in service mapping

simple_ui/templates/angular/partials/directives/services-list.html
https://trello.com/c/xMnyanC5/34-as-a-user-on-mobile-i-need-to-be-able-to-see-the-whole-title-location-and-service-provider-name-in-a-listing-clearly
=> Change order of information on services list item

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/services/LocationService.js, simple_ui/templates/angular/partials/directives/services-list.html, simple_ui/templates/angular/partials/location.services.html
- plus small name refactor
https://refugeeinfo.atlassian.net/browse/RIW-651
=> RIW-651 - showing assigned Service Types bug fix

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/location.services.html
https://trello.com/c/r5H0LVpz/70-highlight-category-same-as-mobile-view-for-desktop
=> Chosen service type highlighted on desktop view

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
- that recenter map on chosen region
https://trello.com/c/FPMNTDPJ/33-as-a-user-on-mobile-if-i-limited-the-map-view-to-a-certain-area-i-need-that-to-be-reflected-in-the-service-listing
=> Additional control button on map

simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss
- moved above zoom in / zoom out buttons
- icon replaced with translatable label
- removed title on hover
=> 'Reset map' control button improvements

simple_ui/static/js/refugeeApp/services/LocationService.js
https://refugeeinfo.atlassian.net/browse/RIW-664
=> RIW-664 - display services for region and its relatives

simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/services-map.html
https://refugeeinfo.atlassian.net/browse/RIW-665
=> RIW-665 - icon size change on service info pop up (mobile)

simple_ui/static/js/refugeeApp/controllers/LocationServicesController.js, simple_ui/static/js/refugeeApp/directives/servicesMap.js, simple_ui/static/scss/main.scss, simple_ui/templates/angular/partials/directives/search-bar.html, simple_ui/templates/angular/partials/location.services.html
plus reset button inline with search bar
https://refugeeinfo.atlassian.net/browse/RIW-666
=> RIW-666 - Swap search bar with panel tabs on mobile devices.

simple_ui/static/scss/main.scss
https://refugeeinfo.atlassian.net/browse/RIW-666
=> RIW-666 - fix search bar on 768px width resolution
